name: Playbook
description: 'CIが落ちた時にどのように対応するべきかを書く'
inputs:
  message:
    description: 'How to fix?'
    required: true
runs:
  using: "composite"
  steps:
    - name: Playbook
      uses: actions/github-script@v7
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          const message = process.env.INPUT_MESSAGE
            // {{ JOB_NAME }} 
            .replace(/{{\s{0,5}JOB_NAME\s{0,5}}}/g, context.job);
          core.summary.addRaw(message, true);
          await core.summary.write();
          core.setFailed(message);
